
hibernate:
  dialect: "org.asqatasun.dialect.AsqatasunMySQL5InnoDBDialect"
jdbc:
  driverClassName : "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://localhost:3306/asqatasun"
  user: "root"
  password: bou

jpa:
  showSql: true
#contentsAdapter
tempFolderRootPath: /tmp/

# max concurrent audit configuration
pageAuditConcurrentMaxSize: 1
scenarioAuditConcurrentMaxSize: 1
uploadAuditConcurrentMaxSize: 1
siteAuditConcurrentMaxSize: 1

# ProxyConfiguration
# CAUTION: these variables *must* be present (empty), even if no proxy is used
# Examples for $proxyExclusionUrl:
#  proxyExclusionUrl=127.0.0.1
#  proxyExclusionUrl=127.0.0.1;localhost;myhost;
#  proxyExclusionUrl=myhost
#  proxyExclusionUrl=mydomain.com
#  proxyExclusionUrl=internalhost;mydomain.com
proxyHost:
proxyPort:
proxyUser:
proxyPassword:
proxyExclusionUrl:
pathToPreSetFirefoxProfile:

# timeout from which a page is seen as fully loaded in seconds
pageLoadTimeout: 20

# bypass initial check of URL before effective launch of audit.
# CAUTION : bypassing this control may lead to test error pages.
# Only use for debug purpose when setting network properties.
# The value MUST be equals to false or true
bypassUrlCheck: false
